//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpnK22CNT3Lesson10Db.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NpnAccount
    {
        public string NpnID { get; set; }
        public string NpnUserName { get; set; }
        public string NpnPassword { get; set; }
        public string NpnFullName { get; set; }
        public string NpnEmail { get; set; }
        public Nullable<bool> NpnActive { get; set; }
    }
}
