//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpnBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class npnKetqua
    {
        public string NpnMaSV { get; set; }
        public string NpnMaMH { get; set; }
        public string NpnDiem { get; set; }
    
        public virtual npnMonHoc npnMonHoc { get; set; }
        public virtual npnSinhVien npnSinhVien { get; set; }
    }
}
