//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpnBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class npnKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public npnKhoa()
        {
            this.npnSinhViens = new HashSet<npnSinhVien>();
        }
    
        public string NpnMaKH { get; set; }
        public string NpnTenKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<npnSinhVien> npnSinhViens { get; set; }
    }
}
