//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NpnBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class npnSinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public npnSinhVien()
        {
            this.npnKetquas = new HashSet<npnKetqua>();
        }
    
        public string NpnMaSV { get; set; }
        public string NpnHoSV { get; set; }
        public string NpnTenSV { get; set; }
        public Nullable<System.DateTime> NpnNgaySinh { get; set; }
        public Nullable<bool> NpnPhai { get; set; }
        public string NpnMaKH { get; set; }
        public string NpnNoiSinh { get; set; }
        public string NpnHocBong { get; set; }
        public string NpnDiemTrungBinh { get; set; }
    
        public virtual npnKhoa npnKhoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<npnKetqua> npnKetquas { get; set; }
    }
}
